language: node_js
node_js:
- "7"

install: 
- npm install 
- npm install -g firebase-tools

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the master branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

after_success:
   - firebase deploy --token ${FIREBASE_TOKEN}